config/routes.rb
Tranquilapi::Application.routes.draw do
  resources :users

  resources :services do
    member do
      get "fetch"
      get "next" # get's page two of the raw html
    end
  end

  root 'services#index'

  

end

app/models/service.rb
# this is the parent class of webexchange_services, coast_services, and amion_services etc

class Service < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  @date_array = nil
  
  # download remote page and store the raw html
  def fetch
  end
  
  # parse pre-fetched raw html into a dict or hash
  def parse
  end
  
  def date_range
    if date_start and date_end
      "#{date_start.strftime("%D") if date_start }-#{date_end.strftime("%D") if date_end}"
    else
      nil
    end
  end
  
  def date_start
    h = date_array.first
    if h and h[:shift_start]
      Time.parse(h[:shift_start])
    else
      nil
    end
  end
  
  def date_end
    h = date_array.last
    if h and h[:shift_start]
      Time.parse(h[:shift_start])
    else
      nil
    end
  end
  
  def date_array
    @date_array ||= (parse || [])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy, :fetch, :next]
  before_action :restrict_access_to_admins_unless_none_exist, only: [:new, :edit, :update, :create, :destroy]
  before_action :restrict_access_to_users_unless_none_exist, only: [:show]
  
  include ActionView::Helpers::DateHelper # to use time_ago_in_words

  # renders page two of the raw html
  def next
    respond_to do |format|
      if @service
        format.html { render inline: @service.raw_html_2 || "There are no data for #{@service.name} as of #{ time_ago_in_words( @service.updated_at) } ago. Please try to fetch."}
      else
        format.html { render inline: 'not found' }
      end
    end
    
  end
  
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    
    respond_to do |format|
      format.html
      format.json { render json: @services.collect {|e| e.as_json(only: [:id, :name, :remote_id, :type, :slug])} }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @specific_date = params[:date] ? Date.parse( params[:date]) : nil
    
    respond_to do |format|
      if @service
        format.html { render inline: @service.raw_html_1 || "There are no data for #{@service.name} as of #{ time_ago_in_words( @service.updated_at) } ago. Please try to fetch."}
        format.json { render json: @specific_date ? @service.parse.select {|e| @specific_date == e[:shift_start].in_time_zone.to_date } : @service.parse }
      else
        format.html { render inline: 'not found' }
        format.json { render json: {error: "not found"}, status: :unprocessable_entity }
      end
    end
  end

  def fetch
    @service.fetch
    redirect_to service_path @service
  end
  
  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :remote_id, :start_date, :raw_html_1, :raw_html_2, :type, :slug)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service, url: service_url( @service )) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :remote_id, "Remote ID" %><br>
    <%= f.text_field :remote_id %>
  </div>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.select :type, ["WebexchangeService", "AmionService"] %>
  </div>

	<% if f.object.slug.present? %>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
	<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1>Listing services</h1>
<p>This is the Schedules API, which interfaces with Amion and Webexchange to provide schedule data in a machine-readable format.</p>

<% if @services.size > 0 %>
	<p>To get a list of services</p>
	<code>GET <%= services_url + ".json" %></code>
	<% [@services.first].each do |service| %>
	<p>To see the raw page</p>
	<code>GET <%= service_url(service) %></code>
	<p>To see the json</p>
	<code>GET <%= service_url(service) %>.json</code>
	<p>To see the json for today only</p>
	<code>GET <%= service_url(service) %>.json?date=<%= Time.now.strftime("%Y-%m-%d") %></code>
	<% end %>
	<p>Enjoy!</p>
<% else %>
	<p>There are no services defined yet. To seed, do the following:</p>
	<code>rake webexchange:seed</code>
	<code>rake amion:seed</code>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Remote page</th>
      <th>Date range</th>
      <th>Type</th>
      <th>Updated</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= link_to service.name.html_safe, service_path( service ) + ".json" %> (<%= link_to "today's shifts", service_path(service) + ".json?date=#{ Time.now.strftime("%Y-%m-%d")}"%>)</td>
        <td><%= link_to service.remote_id, service_path(service) %></td>
        <td><%= service.date_range %></td>
        <td><%= service.type %></td>
        <td><%= time_ago_in_words service.updated_at %> ago (<%= link_to "update", fetch_service_path(service) %>)</td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service_path( service ), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Remote:</strong>
  <%= @service.remote_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @service.start_date %>
</p>

<p>
  <strong>Raw html 1:</strong>
  <%= @service.raw_html_1 %>
</p>

<p>
  <strong>Raw html 2:</strong>
  <%= @service.raw_html_2 %>
</p>

<p>
  <strong>Type:</strong>
  <%= @service.type %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @service.slug %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>